---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: windows-2012r2
    driver_config:
      box: windows-2012r2
    provisioner:
      require_chef_omnibus: 12

suites:
  - name: default
    run_list:
      - recipe[winrm::default]